server:
  port: 80
spring:
  application:
    name: RJtakeout
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: PASSword1224
  cache:
    redis:
      time-to-live: 3600000
  redis:
    database: 0
    host: localhost
    port: 6379


mybatis-plus:
  configuration:
#    下划线映射驼峰命名
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
#      雪花算法id
      id-type: assign_id


rjTakeOut:
#  path: /Users/saladday/Pictures/img/
  path: G:\img\